Make SonarCloud project key and organization inputs optional in analyse.yml and update token handling in licences-analysis-maven.yml

diff --git a/.github/workflows/licences-analysis-maven.yml b/.github/workflows/licences-analysis-maven.yml
--- a/.github/workflows/licences-analysis-maven.yml
+++ b/.github/workflows/licences-analysis-maven.yml
@@ -17,7 +17,7 @@ on:
         description: 'The Dash repository URL'
         required: false
         type: string
-        default: https://github.com/${{ github.repository }}
+        default: ''
       create-review:
         description: 'Create a review for the license analysis'
         required: false
@@ -44,9 +44,18 @@ jobs:
           distribution: 'zulu'
           cache: maven
 
+      - name: check if token required
+        id: check-token
+        if: ${{ inputs.create-review }}
+        run: |
+          if [ "${{ inputs.create-review }}" = "true" ] && [ -z "${{ secrets.token }}" ]; then
+            echo "Token is required for creating a review but not provided."
+            exit 1
+          fi
+
       - name: Build with Maven and check dependencies with dash
         run: |
-            if [ -n "${{ secrets.token }}" ]; then
+            if [ -n "${{ input.create-review }}" ]; then
               mvn --batch-mode --update-snapshots verify -Ddash.projectId=${{ inputs.dash_project_id }} -Ddash.repo=${{ inputs.dash_repo }} -Ddash.iplab.token=${{ secrets.token }} -P dash
             else
               mvn --batch-mode --update-snapshots verify -P dash
